### ISSUE TITLE
Chase score switching (suggestion)

### ISSUE THREAD

**Issue by QaleQ** [hettoo/racesow#8]
Would be nice if the "/chase score" cmd would allow you to switch between tied players. Especially when noone on the server has a time set yet, or when people just happen to be tied, allthough the latter is so rare that it's not really important!

**Comment by hettoo** [comment]
Done.

**Comment by QaleQ** [comment]
i've tried this, since other updates you made after this have been included ingame, but this is still not working for some reason! don't know how to re-open closed issues :p

**Comment by hettoo** [comment]
Probably needs a server restart.
Issue being fixed in the repo doesn't necessarily mean it is already fixed on contemporary servers running racesow. ^^
I'm trying to update mine as soon as possible, but won't restart unless it is empty.
